config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#new'
  resources :messages, only: [:index, :create]
  resources :groups, only: [:index, :new, :create, :update, :edit, :show]
  resources :users, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :messages
  has_many :user_groups
  has_many :users, through: :user_groups
  validates :name, presence: true

  def newest_message
    messages.last.body unless messages.last.nil?
  end

  def newest_message_time
    messages.last.created_at unless messages.last.nil?
  end

  def order_by_message
    sort{|a,b| a.newest_message_time.to_s <=> b.newest_message_time.to_s}
  end

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :user_groups
  has_many :groups, through: :user_groups
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  def after_sign_out_path_for(resource)
    new_user_session_path
  end

  def after_sign_in_path_for(resource)
    new_group_path
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @users = User.all
    respond_to do |format|
      format.json
    end
  end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def edit
    @group = Group.find(params[:id])
  end

  def show
    @groups = current_user.groups.eager_load(:users).sort{|b,a| a.newest_message_time.to_s <=> b.newest_message_time.to_s}
    @group = Group.eager_load(:users, :messages).find(params[:id])
    @message = Message.new
  end

  def update
    group = Group.find(params[:id])
    if group.update(group_params)
      flash[:notice] = "グループを更新しました。"
      redirect_to group
    else
      flash[:notice] = "タイトルを入力してください。"
      redirect_to action: 'new'
    end
  end

  def create
    group = Group.create(group_params)
    if group.save
      flash[:notice] = "グループが作成されました。"
      redirect_to group
    else
      flash[:notice] = "タイトルを入力して下さい。"
      redirect_to action: 'new'
    end
  end

  private
  def group_params
    params.require(:group).permit(
      :name,
      user_ids: [])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!
  def index
    group = Group.eager_load(:messages, :users).find(params[:id])
    @messages = group.messages.order("created_at ASC")
    respond_to do |format|
      format.html
      format.json
    end
  end

  def create
    @message = Message.new(create_params)
    respond_to do |format|
      if @message.save
        format.html do
          redirect_to controller: 'groups', action: 'show', id: message.group
        end
        format.json
      else
        format.html do
          flash[:notice] = "本文を入力して下さい。"
          redirect_to controller: 'groups', action: 'show', id: message.group
        end
        format.json do
          flash[:notice] = "本文を入力して下さい。"
        end
      end
    end
  end

  private
  def create_params
    params.require(:message).permit(
      :body, :image, :group_id).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    name = params[:user_name]
    @users = User.where('name LIKE ?',"%#{name}%" )
    respond_to do |format|
      format.json
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = form_for @group do |f|
    = render partial: "layouts/group-flash-message"
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :name, "グループ名", class: "chat-group-form__label"
      .chat-group-form__field--right
        = f.text_field :name, placeholder: "グループ名を入力してください。", class: "chat-group-form__input"
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :user, "チャットメンバーを追加", class: "chat-group-form__label"
      .chat-group-form__field--right
        = f.collection_check_boxes(:user_ids, User.all, :id, :name) do |t|
          .chat-group-form__check
            = t.label { t.check_box + t.text }
    .chat-group-form__field.clearfix
      .chat-group-form__field--right
        = f.submit "作成する", class: "chat-group-form__action-btn"

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = form_for @group do |f|
    = render partial: "layouts/group-flash-message"
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :name, "グループ名", class: "chat-group-form__label"
      .chat-group-form__field--right
        = f.text_field :name, placeholder: "グループ名を入力してください。", class: "chat-group-form__input"
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        %label.chat-group-form__label チャットメンバーを追加
      .chat-group-form__field--right
        .chat-group-form__search
          %input#group_user_name.chat-group-form__input{placeholder: "チャットメンバーを入力して下さい。" }
        #user-search-result
    .chat-group-form__field.clearfix
      .chat-group-form__field--left
        = f.label :user, "チャットメンバー", class: "chat-group-form__label"
      .chat-group-form__field--right
        #chat-group-users
          %p.chat-group-user__name
    .chat-group-form__field.clearfix
      .chat-group-form__field--right
        = f.submit "作成する", class: "chat-group-form__action-btn", id: "js-group-submit"

app/views/groups/show.html.haml
.chat
  = render partial: 'messages/chat-side', locals: {groups: @groups}
  = render partial: 'messages/chat-main', locals: {group: @group, message: @message}

app/views/layouts/_flash-message.html.haml
- flash.each do |key, value|
  - if value == notice
    = content_tag(:div, value, class: "alert alert-success")
  - if value == alert
    = content_tag(:div, value, class: "alert alert-danger")

app/views/layouts/_group-flash-message.html.haml
- flash.each do |key, value|
  .chat-group-form__errors.clearfix
    %h2 グループが作成されません。
    %ul
    - if value == notice
      = content_tag(:li, value)
    - if value == alert
      = content_tag(:li, value)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    %link{href: "//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css", rel: "stylesheet"}
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    - unless controller_name == "groups"
      #js-flash
        = render partial: "layouts/flash-message"
    = yield

app/views/messages/_chat-main.html.haml
.chat-main
  .chat-header
    .chat-header__left
      %h2
        = group.name
      %p.chat-header__users
        Members:
        = render partial: 'messages/member', collection: group.users, as: "user"
    .chat-header__right
      .chat-header__edit-btn
        = link_to "編集", edit_group_path(group)
  .chat-body
    %ul.chat-messages
      -# = render partial: 'message', collection: @messages
  .chat-footer
    = form_for message do |f|
      .new_message
        .chat-footer__body
          = f.text_area :body, class: "chat-footer__textarea", id: "js-input"
          = f.hidden_field :group_id, value: group.id
          %label.chat-footer__file
            = f.file_field :image
            %i.fa.fa-image
        = f.submit "送信", class: "chat-footer__submit", id: "js-submit"

app/views/messages/_chat-side.html.haml
.chat-side
  .chat-user
    %h5
      = current_user.name
    .chat-user__actions
      = link_to new_group_path, class: "chat-user__action" do
        %i.fa.fa-pencil-square-o
      = link_to edit_user_registration_path, class: "chat-user__action" do
        %i.fa.fa-cog
  %ul.chat-groups
    = render partial: 'messages/group', collection: groups

app/views/messages/_group.html.haml
= link_to group_path(group) do
  %li.chat-group
    %p.chat-group__name
      = group.name
    %p.chat-group__message
      = group.newest_message

app/views/messages/_member.html.haml
%span.chat-header__user
  = user.name

app/views/messages/_message.html.haml
%li.chat-message
  .chat-message__header
    %p.chat-message__name
      = current_user.name
    %p.chat-message__time
      = message.created_at.strftime("%m/%d %H:%M")
  %br
  %p.chat-message__body
    = message.body
  = image_tag message.image if message.image?